export const COACH_KITS = [
  {
    id: 'choice',
    icon: '🔀',
    title: '我在几个选项里反复纠结',
    shortTitle: '纠结选择型',
    desc: '适合二选一、多选一，帮你比较利弊和真正看重的东西。',
    framework: '利弊清单 + 价值排序',
    tone: '结构化比较',
    resultTitle: '选择变清楚了一点',
    summaryTitle: '你现在更清楚的 3 件事',
    nextActionTitle: '下一步小行动',
    nextAction: '选一个最小可验证动作，在 24 小时内推进一下，而不是继续空想。',
    steps: [
      { title: '选项 A 是什么？', placeholder: '例如：接这个 offer / 留在现在公司', hint: '如果不止两个选项，先写最纠结的那个。', type: 'text' },
      { title: '选项 A 的好处', placeholder: '每行写一个好处。', hint: '尽量写事实，不用急着评价。', type: 'textarea' },
      { title: '选项 B 是什么？', placeholder: '例如：继续等待 / 换一个方向', hint: '', type: 'text' },
      { title: '选项 B 的好处', placeholder: '每行写一个好处。', hint: '', type: 'textarea' },
      { title: '你最不想牺牲什么？', placeholder: '例如：稳定、成长、自由、关系、健康、钱、时间...', hint: '这是价值排序，不是标准答案。', type: 'textarea' },
    ],
  },
  {
    id: 'emotion',
    icon: '🌧️',
    title: '我情绪很乱，没法判断',
    shortTitle: '情绪降噪型',
    desc: '适合焦虑、害怕、冲动时先降噪，再慢慢看清问题。',
    framework: '情绪命名 + 最坏情况承受度',
    tone: '安抚降噪',
    resultTitle: '先把情绪从决定里分出来',
    summaryTitle: '此刻可以先放下的东西',
    nextActionTitle: '下一步小行动',
    nextAction: '先等情绪从 8 分降到 5 分以下，再做不可逆决定。',
    steps: [
      { title: '现在最强烈的情绪是什么？', placeholder: '例如：焦虑、委屈、害怕、兴奋、愤怒、内疚...', hint: '先命名，不急着解决。', type: 'text' },
      { title: '这个情绪在提醒你什么？', placeholder: '它可能在保护什么需求？', hint: '情绪不是敌人，它可能是一封提醒信。', type: 'textarea' },
      { title: '最坏情况是什么？你能承受几分？', placeholder: '写下最担心的事，以及 1-10 分的承受度。', hint: '不是吓自己，是把模糊恐惧具体化。', type: 'textarea' },
      { title: '现在先不做决定，会损失什么？', placeholder: '如果可以暂停 24 小时，代价是什么？', hint: '', type: 'textarea' },
    ],
  },
  {
    id: 'action',
    icon: '🏃',
    title: '我知道方向，但迟迟动不起来',
    shortTitle: '行动启动型',
    desc: '适合已经有方向但卡在拖延、害怕开始、执行阻力上。',
    framework: '阻力拆解 + 5 分钟启动',
    tone: '行动推进',
    resultTitle: '把决定变成一个能开始的动作',
    summaryTitle: '真正卡住你的地方',
    nextActionTitle: '5 分钟启动动作',
    nextAction: '只做一个小到不会失败的动作，先让这朵花长出第一片叶子。',
    steps: [
      { title: '你其实已经倾向于做什么？', placeholder: '写下那个你心里知道但一直没开始的方向。', hint: '', type: 'textarea' },
      { title: '你迟迟没动的主要阻力是什么？', placeholder: '例如：怕失败、太麻烦、不知道第一步、没人支持...', hint: '阻力写出来，就已经小了一点。', type: 'textarea' },
      { title: '如果只做 5 分钟，第一步是什么？', placeholder: '小到可以马上做，例如打开资料、发一条消息、列 3 个问题。', hint: '', type: 'textarea' },
      { title: '什么时候做？', placeholder: '给它一个具体时间：今天 20:30 / 明早起床后...', hint: '没有时间点的行动，很容易继续漂着。', type: 'text' },
    ],
  },
  {
    id: 'info',
    icon: '🔎',
    title: '我缺信息，不敢决定',
    shortTitle: '信息验证型',
    desc: '适合不知道该查什么、问谁、如何低成本试错的情况。',
    framework: '关键未知项 + 低成本验证',
    tone: '调研任务清单',
    resultTitle: '把不确定变成可验证任务',
    summaryTitle: '目前最值得补的信息',
    nextActionTitle: '验证计划',
    nextAction: '先验证影响最大的一个未知项，而不是一次性查完所有信息。',
    steps: [
      { title: '你现在最不确定的 3 件事', placeholder: '每行写一个未知项。', hint: '只写会影响选择的未知项。', type: 'textarea' },
      { title: '哪一个未知项最影响决定？', placeholder: '从上面选一个最关键的。', hint: '', type: 'textarea' },
      { title: '你可以问谁或查哪里？', placeholder: '列出人、资料、平台、过来人。', hint: '优先找真实经验，不只看泛泛建议。', type: 'textarea' },
      { title: '最低成本试错是什么？', placeholder: '例如：试用一天、约一次沟通、先投入 100 元以内...', hint: '', type: 'textarea' },
    ],
  },
  {
    id: 'review',
    icon: '🌸',
    title: '我已经做完了，想复盘一下',
    shortTitle: '复盘提炼型',
    desc: '适合做完决定后，把事实、判断和经验沉淀下来。',
    framework: '事实-判断-经验拆分',
    tone: '成长总结',
    resultTitle: '把这次经历变成可带走的经验',
    summaryTitle: '这次决策留下的线索',
    nextActionTitle: '下次可以保留的做法',
    nextAction: '把最有价值的一条经验写回决策花园，作为下一次选择的提醒。',
    steps: [
      { title: '实际发生了什么？', placeholder: '只写事实，不评价自己。', hint: '', type: 'textarea' },
      { title: '当初哪些判断被验证了？', placeholder: '哪些想法是对的？哪些出乎意料？', hint: '', type: 'textarea' },
      { title: '如果重来一次，你会调整什么？', placeholder: '写一个下次会更早做 / 更少做的动作。', hint: '', type: 'textarea' },
      { title: '这次最值得带走的一句话', placeholder: '例如：当信息不够时，我需要先做小实验，而不是继续脑内消耗。', hint: '这句话可以成为花园里的成长片段。', type: 'textarea' },
    ],
  },
]

export function getCoachKit(id) {
  return COACH_KITS.find(kit => kit.id === id) || COACH_KITS[0]
}
